# Generated by Django 6.0.2 on 2026-05-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New Project', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='Ai generated SQl and Schema', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('complete_json', models.JSONField(blank=True, null=True)),
                ('schema_json', models.JSONField(blank=True, null=True)),
                ('sql_json', models.JSONField(blank=True, null=True)),
                ('seed_json', models.JSONField(blank=True, null=True)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
