# Generated by Django 6.0.2 on 2026-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schemaproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
