# Generated by Django 6.0.2 on 2026-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatsession_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaproject',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
