# Generated by Django 6.0.2 on 2026-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schemaproject_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaproject',
            name='sql_edited_manually',
            field=models.BooleanField(default=False),
        ),
    ]
