# Generated by Django 6.0.2 on 2026-05-20 08:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schemaproject_sql_edited_manually'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('sql', 'SQL agent'), ('schema', 'Schema agent')], max_length=10)),
                ('thread_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('text', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_conver_search__2c0bdd_gin'), models.Index(fields=['user', 'agent', 'thread_id'], name='core_conver_user_id_28f99a_idx')],
            },
        ),
    ]
