"""
Django settings for agent project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR / ".env"

if env_file.exists():
    load_dotenv(env_file)

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Comma-separated list in env (e.g. "agent.example.com,api.example.com").
# Localhost is always present so dev keeps working.
_extra_hosts = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()]
ALLOWED_HOSTS = ["localhost", "127.0.0.1", *_extra_hosts]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.postgres',

    'core',
    "rest_framework",
    "corsheaders",
    # 'django_filters',
    'django_celery_results',
    # 'rest_framework.authtoken',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    # 'dj_rest_auth',
    # 'dj_rest_auth.registration',
    
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS — local origins always allowed; production origins come from env
# (CORS_ALLOWED_ORIGINS="https://app.example.com,https://admin.example.com").
_extra_cors = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    *_extra_cors,
]
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

from corsheaders.defaults import default_headers  # noqa: E402
CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "authorization",
]

# CSRF — same shape as ALLOWED_HOSTS but with scheme (https://...).
_extra_csrf = [o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    *_extra_csrf,
]

# Production security toggles — only apply when DEBUG is off so dev stays simple.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

ROOT_URLCONF = 'agent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agent.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Two paths:
#   Production (DEBUG=False) — parse DATABASE_URL with conn_max_age and SSL.
#   Local (DEBUG=True)       — explicit POSTGRES_* env vars, no SSL.
# `DB_URI` stays exported for the LangGraph PostgresSaver and any other
# raw-psycopg consumers in core/services.

DB_URI = os.getenv("DATABASE_URL")

if not DEBUG:
    # Production / managed Postgres (Render, RDS, Supabase, etc.)
    DATABASES = {
        "default": dj_database_url.parse(
            os.environ["DATABASE_URL"],
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Run `python manage.py collectstatic` before each deploy; STATIC_ROOT is the
# target collectstatic copies into. For serverless/no-nginx deployments, add
# whitenoise (`pip install whitenoise`), insert its middleware right after
# SecurityMiddleware, and set STATICFILES_STORAGE to its compressed backend.

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# User-uploaded files (avatars, attachments, exports).
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

SITE_ID = 1

AUTH_USER_MODEL = "core.CustomUser"

# ── Sample databases ───────────────────────────────────────────────
# Read-only SQLite files shipped with the repo that every new user gets
# automatically as Connection rows on signup. Designed as a registry so
# adding a sample later is a one-line append. The file path is absolute
# (resolved at provision time) — re-provisioning picks up any move.
SAMPLE_DBS = [
    {
        "key": "netflix",
        "name": "Netflix (sample)",
        "database": "netflix",
        "type": "sqlite",
        "dialect": "sqlite",
        "path": BASE_DIR / "samples" / "netflix.sqlite3",
    },
]

# ── Email ──────────────────────────────────────────────────────────
# Default to SMTP. To preview emails in the runserver console during
# development, set EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# in .env. Console mode prints the rendered email instead of sending.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
_email_timeout = os.getenv('EMAIL_TIMEOUT')
if _email_timeout:
    EMAIL_TIMEOUT = int(_email_timeout)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@agent.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Admin notification recipients (used by Django for unhandled-error emails
# and any explicit mail_admins() calls). Comma-separated in DJANGO_ADMIN_EMAIL.
_admin_emails = [e.strip() for e in os.getenv('DJANGO_ADMIN_EMAIL', '').split(',') if e.strip()]
ADMINS = [(e.split('@')[0], e) for e in _admin_emails]

# Frontend origin used to build verification + password-reset links in emails.
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Display name shown in transactional emails. Falls back to DEFAULT_FROM_EMAIL.
EMAIL_SITE_NAME = os.getenv('EMAIL_SITE_NAME', 'DataAgent')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        # apply on individual views via decorator or class attribute
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min',
        'signup': '5/min',
        'password_reset': '5/min',
        # 'resend': '5/min',
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),  
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

PASSWORD_RESET_TIMEOUT = 3600  # 1 hour in seconds




# --- celery ---

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"


# --- Logging ---
#
# All app code logs via `logger = logging.getLogger(__name__)`, which under
# the `core` package becomes `core.sql_agent`, `core.schema_agent_hybrid`,
# `core.services.run_registry`, etc. The `core` logger below catches all of
# those plus anything else under the app namespace.
#
# Production: console only (capture via systemd / docker / Render logs).
# Development: console + rotating file under BASE_DIR/logs/app.log.

LOG_DIR = BASE_DIR / "logs"
if DEBUG:
    LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose" if not DEBUG else "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # App code — sql_agent, schema_agent_hybrid, services, etc.
        "core": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # LangGraph / LangChain — keep at WARNING; flip to INFO for retry
        # / fault-tolerance investigations.
        "langgraph": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "langchain": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

if DEBUG:
    LOGGING["handlers"]["file"] = {
        "level": "INFO",
        "class": "logging.handlers.RotatingFileHandler",
        "filename": LOG_DIR / "app.log",
        "maxBytes": 5 * 1024 * 1024,
        "backupCount": 5,
        "formatter": "verbose",
    }
    for name in ("core", "django.server", "django.request", "langgraph", "langchain"):
        LOGGING["loggers"][name]["handlers"].append("file")